name: Deploy Site

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # Recommended if you intend to make multiple deployments in quick succession.
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      # Builds the docs
      - name: Install and build
        run: |
          python -m pip install --upgrade -r requirements.txt
          jb build book

      # Configures GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: book/_build/html # The folder the action should deploy.
          clean: true
          clean-exclude: |
            .nojekyll
